dependencies {
  compile project(path: ':coral-hive')
  compile project(path: ':coral-spark')

  testCompile(deps.'hive'.'hive-exec-core') {
    exclude group: 'org.apache.calcite', module: 'calcite-core'
  }
  testCompile deps.'hadoop'.'hadoop-mapreduce-client-core'
  testCompile deps.'kryo'
  testCompile 'commons-io:commons-io:2.5'
}
